#!/bin/bash
#
# Start a new branch: `git checkout main` and `git checkout -b <name>`.
#
# $1 = branch

set -e  # stop on error

SCRIPTS="$(dirname "$0")"

main=$("$SCRIPTS"/git-default-branch)

git checkout "$main"

git checkout -b "$1"
