#!/bin/bash
#
# Prints the (GitHub) fork and upstream remotes.


set -e  # stop on error


SCRIPTS="$(dirname "$0")"

main=$("$SCRIPTS"/git-default-branch)

remote_main_name=$(git config --get branch.${main}.remote || echo)
remote_main_url=$(git remote get-url "$remote_main_name" 2>/dev/null || echo)
if [[ ! "$remote_main_url" ]]; then
  echo >&2 "Error: no remote found for the $main branch"
  exit 1
fi
fork="$remote_main_name"
fork_url="$remote_main_url"
upstream="$remote_main_name"
upstream_url="$remote_main_url"


remote_origin_url=$(git remote get-url "origin" 2>/dev/null || echo)
remote_upstream_url=$(git remote get-url "upstream" 2>/dev/null || echo)
if [[ "$remote_origin_url" && "$remote_upstream_url" ]]; then
  fork="origin"
  fork_url="$remote_origin_url"
  upstream="upstream"
  upstream_url="$remote_upstream_url"
else
  hub_user=$("$SCRIPTS"/git-hub-user)
  if [[ ! "$hub_user" ]]; then
   echo >&2 "Error: github.com username is required"
   exit 1
  fi
  remote_username_url=$(git remote get-url "$hub_user" 2>/dev/null || echo)
  if [[ "$remote_username_url" && "$remote_origin_url" ]]; then
    fork="$hub_user"
    fork_url="$remote_username_url"
    upstream="origin"
    upstream_url="$remote_origin_url"
  elif [[ "$remote_username_url" && "$remote_upstream_url" ]]; then
    fork="$hub_user"
    fork_url="$remote_username_url"
    upstream="upstream"
    upstream_url="$remote_upstream_url"
  fi
fi

if [[ "$1" == "--fork" ]]; then
  printf "$fork\t$fork_url\n"
elif [[ "$1" == "--upstream" ]]; then
  printf "$upstream\t$upstream_url\n"
else
  printf "fork:        $fork\t$fork_url\n"
  printf "upstream:    $upstream\t$upstream_url\n"
fi
