#!/bin/bash
#
# Create a GitHub pull request: calls `git prepare` and `git push`,
# followed by one of the following: `gh pr create`, `hub pull-request`, or
# opening a GitHub compare URL.

set -e  # stop on error

SCRIPTS="$(dirname "$0")"

upstream=$("$SCRIPTS"/git-hub-remotes --upstream | cut -f1)
fork=$("$SCRIPTS"/git-hub-remotes --fork | cut -f1)
current=$(git symbolic-ref --short HEAD)


git prepare "$upstream"

git push "$fork"

sleep 1

# If the `gh` command is available, use it to create and open the pull request.
if which hub > /dev/null; then
  echo
  echo "Creating pull request..."
  echo "> gh pr create --fill --web"
  gh pr create --fill --web
  exit
fi

# If the `hub` command is available, use it to create and open the pull request.
if which hub > /dev/null; then
  echo
  echo "Creating pull request..."
  echo "> hub pull-request --browse"
  hub pull-request --browse
  exit
fi


# Otherwise, construct a compare URL and attempt to open it.

upstream_url=$("$SCRIPTS"/git-hub-remotes --upstream | cut -f2)
fork_url=$("$SCRIPTS"/git-hub-remotes --fork | cut -f2)
upstream_repo=$(echo "$upstream_url" | sed 's/.*github.com.//' | cut -f1 -d.)
fork_repo=$(echo $"fork_url" | sed 's/.*github.com.//' | cut -f1 -d/)
url="https://github.com/$upstream_repo/compare/master...$fork_repo:$branch"

echo
BROWSER_COMMANDS="open xdg-open cygstart x-www-browser google-chrome firefox"
for $browser in $BROWSER_COMMANDS; do
  if which $browser > /dev/null; then
    echo "Opening GitHub compare page..."
    echo "> $browser $url"
    $browser "$url"
    exit
  fi
done

echo "Error: Could not automatically open the GitHub compare page."
echo "Please go to the following URL to create the pull request:"
echo
echo "    $url"
