#!/bin/bash
#
# Sync the current branch: pull from upstream and push to fork
#
# $1 = upstream (defaults to `git hub-remotes --upstream`)
# $2 = fork (defaults to `git hub-remotes --fork`)
# $3 = branch (defaults to the current branch)

set -e  # stop on error

SCRIPTS="$(dirname "$0")"

upstream=${1:-$("$SCRIPTS"/git-remotes --upstream | cut -f1)}
fork=${2:-$("$SCRIPTS"/git-remotes --fork | cut -f1)}
current=$(git symbolic-ref --short HEAD)
branch=${3:-$current}


echo "Pulling latest commits from $upstream/$branch to $current..."
echo "> git pull --prune --tags $upstream $branch"
git pull --prune --tags $upstream $branch
echo "Done."

if [[ "$upstream" != "$fork" ]]; then
  echo "Pushing $current to $fork/$branch..."
  echo "> git push --prune $fork $current:$branch"
  git push --prune $fork $current:$branch
  echo "Done."
fi
