#!/bin/bash
#
# Finish a branch: `git checkout main`, `git sync`, and `git tidy`.

set -e  # stop on error


SCRIPTS="$(dirname "$0")"

main=$("$SCRIPTS"/git-hub-main)

git checkout "$main"

git sync

git tidy
